example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from wishlist.views import show_xml 
from wishlist.views import show_json
from wishlist.views import show_json_by_id #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_xml_by_id #sesuaikan dengan nama fungsi yang dibuat


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), #sesuaikan dengan nama fungsi yang dibuat
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'), #sesuaikan dengan nama fungsi yang dibuat
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_json #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_json_by_id #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_xml_by_id #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import register 
from wishlist.views import login_user 
from wishlist.views import logout_user 
from wishlist.views import wishlist_ajax 
from wishlist.views import wishlist_ajax_submit

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), #sesuaikan dengan nama fungsi yang dibuat
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'), #sesuaikan dengan nama fungsi yang dibuat
    path('register/', register, name='register'),
    path('login/', login_user, name='login'), 
    path('logout/', logout_user, name='logout'), 
    path('ajax/', wishlist_ajax, name='ajax'), 
    path('ajax/submit', wishlist_ajax_submit, name='ajax_submit'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from .models import BarangWishlist
from django import forms
from django import forms

class AjaxForm(forms.ModelForm):    
    class Meta:
        model = BarangWishlist
        fields = ['nama_barang', 'harga_barang', 'deskripsi']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.forms import AjaxForm
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Vinsensius Ferdinando',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def wishlist_ajax(request):
    context = {
        'nama': 'Vinsensius Ferdinando',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def wishlist_ajax_submit(request):
    if (request.method == "POST"):
        form = AjaxForm(request.POST or None)
        if (form.is_valid()):
            nama = form.cleaned_data['nama_barang']
            harga = form.cleaned_data['harga_barang']
            deskripsi = form.cleaned_data['deskripsi']
            new_wishlist_item = BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
            return JsonResponse({'nama_barang':nama,
                                'harga_barang':harga,
                                'deskripsi':deskripsi
                                })

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

example_app/templates/index1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}		
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
  <head>
    <style>
        ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
        }
        li {
          float: left;
        }
        li a {
          display: block;
          padding: 8px;
          background-color: rgb(198, 201, 201);
        }
        </style>
        </head>
        <body>
        
        <ul>
          <li><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">{{nama}}</a></li>
          <li><a href="{% url 'wishlist:logout' %}">Logout</a></li>
        </ul>
        <th><b>Klik nama untuk kejutan!</b></th>
          <h5>Sesi terakhir login: {{ last_login }}</h5>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist dengan bootstrap</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  
  <body>
    <h3 class="text-center">
        Barang yang ada di wishlist:
        <small class="text-muted">Buatan Vinsensius Ferdinando (2106751221)</small>
    </h3>
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th scope="col", class="text-center"><b>Nama Barang</b></th>
            <th scope="col", class="text-center" ><b>Harga Barang</b></th>
            <th scope="col", class="text-center" ><b>Deskripsi</b></th>
            </tr>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% for barang in list_barang %}
            <tr>
                <th class="text-xl-center">{{barang.nama_barang}}</th>
                <th class="text-xl-center">{{barang.harga_barang}}</th>
                <th class="text-xl-center">{{barang.deskripsi}}</th>
            </tr>
        {% endfor %}
    </table>
    <figure class="text-center">
        <blockquote class="blockquote">
          <p>Masukin wishlist doang, dibayar nanti</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          - Vinsensius Ferdinando<cite title="Source Title">(2106751221)</cite>
        </figcaption>
      </figure>
   <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
  </body>
</html>

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
  <style>
    ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    }
    li {
    float: left;
    }
    li a {
    display:inline-block;
    padding: 8px;
    background-color: rgb(198, 201, 201);
    }
  </style>
  <ul>
    <li><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">{{nama}}</a></li>
    <li><a href="{% url 'wishlist:logout' %}">Logout</a></li>
  </ul>
  <th><b>Klik nama untuk kejutan!</b></th>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="{% static 'wishlist_ajax.js' %}"></script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wishlist dengan Bootstrap dan Ajax</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</head>

<body>
  <h5><mark>Nama: <b>{{nama}}</b></mark></h5>
  <h5><mark>Sesi terakhir login: {{ last_login }}</mark></h5>
  <h3 class="text-center">
    Barang yang ada di wishlist:
    <small class="text-muted">Buatan Vinsensius Ferdinando (2106751221)</small>
  </h3>
  <table id="table" class="table table-hover table-striped table-bordered">
    <tr>
      <th class="item-table-cell text-center">Nama Barang</th>
      <th class="item-table-cell text-center">Harga Barang</th>
      <th class="item-table-cell text-center">Deskripsi</th>
    </tr>
  </table>

  <figure class="text-center">
    <blockquote class="blockquote">
    <p>Masukin wishlist doang, dibayar nanti</p>
    </blockquote>
    <figcaption class="blockquote-footer">
    - Vinsensius Ferdinando<cite title="Source Title"> (2106751221)</cite>
    </figcaption>
  </figure>

  <div class="container">
    <h3 class="text-center"><mark>Masukkan item wishlist baru anda!</mark></h3>
    <form id="form">
      {% csrf_token %}
      <table class="table table-hover mx-auto" style="width: inherit">
        <tr>
          <td class="text-right">Nama Barang : </td>
          <td><input id="nama-barang-input" type="text" name="nama_barang" placeholder="Nama Barang"></td>
        </tr>
        <tr>
          <td class="text-right">Harga Barang : </td>
          <td><input id="harga-barang-input" type="text" name="harga_barang" placeholder="Harga Barang"></td>
        </tr>
        <tr>
          <td class="text-right">Deskripsi : </td>
          <td><input id="deskripsi-input" type="text" name="deskripsi" placeholder="Deskripsi"></td>
        </tr>
          <td colspan="2" class="text-center"><button id="create-button" type="submit" class="px-5 py-1.5 bg-success text-white">Save</button>
        </td>
    </table>
    </form>
  </div>

</body>

{% endblock content %}